### ISSUE TITLE
how to build the PyQt5 in Openwrt

### ISSUE THREAD

**Issue by Lancermy** [cnayan/wifiRuleTogglePythonGui#1]
Can you help me ?when I build the PyQt5 in Openwrt .it comes bugs.Can you show me?thank you so much.
![_ykfi _ug v 0nhvr x7o](https://user-images.githubusercontent.com/40566195/41847985-8b4b528e-78ae-11e8-8977-9baf60f3a85d.png)

**Comment by cnayan** [comment]
This issue is not relevant to this project. Depending on your python version, look for wheel files here: [https://pypi.org/simple/pyqt5/](https://pypi.org/simple/pyqt5/)

More: https://stackoverflow.com/a/21577824/315151
https://pypi.org/project/PyQt5/#files
